version: "3.9"
services:
  mongo:
    image: mongo
    volumes:
      - mongoVol:/data/db
    networks:
      - private-net-1
  flask-app:
    build:
      context: flask-app
    depends_on:
      - mongo
    networks:
      - private-net-1
      - public-net-1
  nginx:
    build:
      context: nginx
    ports:
      - "8080:80"
    depends_on:
      - flask-app
    networks:
      - private-net-1
volumes:
  mongoVol: {}
networks:
  public-net-1:
    driver: bridge
  private-net-1:
    driver: bridge
