name: Students Presubmit Tests
on: [push]
jobs:
  BashFinalProjectTest:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    if: ${{ startsWith(github.ref, 'refs/heads/bash_project/')  }}
    steps:
      - uses: actions/checkout@v2
      - name: Run test cases
        run: |
          cd bash_project
          sudo bash test.sh
  NetworkingProjectTest:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/heads/networking_ex/')  }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      COURSE_STAFF_SSH_KEY: ${{ secrets.COURSE_STAFF_SSH_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
      - name: Networking Ex - VPC Check
        run: |
          cd 03_networking_ex/test
          bash test_vpc.sh
      - name: Networking Ex - Basion Check
        run: |
          mkdir -p ~/.ssh
          cp 03_networking_ex/test/ssh_config ~/.ssh/config
          cd 03_networking_ex/test
          bash test_bastion.sh
      - name: Networking Ex - Keys Rotation Check
        run: |
          cd 03_networking_ex/test
          bash test_rotation.sh
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            aiohttp
      - run: |
          cd 03_networking_ex/tls_webserver
      - name: Networking Ex - TLS Hnadshake - Getting Eve certificate
        run: |
          cd 03_networking_ex
          bash test/test_tls.sh eve
      - name: Networking Ex - TLS Hnadshake - Bad client test message encryption
        run: |
          cd 03_networking_ex
          bash test/test_tls.sh bad-msg
      - name: Networking Ex - TLS Hnadshake - Full handshake process
        run: |
          cd 03_networking_ex
          bash test/test_tls.sh